### ISSUE TITLE
Is this Package is working with Laravel 6.0

### ISSUE THREAD

**Issue by Spartaa** [appointer/swaggervel#25]
Is this Package is working with Laravel 6.0

**Comment by fgreinus** [comment]
I dont' know as  am currently not working in the php ecosystem anymore. Try it out and if not - i'd welcome your PR.

**Comment by Spartaa** [comment]
Okay I will update you

**Comment by Spartaa** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for appointer/swaggervel ^2.4 -> satisfiable by appointer/swaggervel[v2.4].
    - Conclusion: remove laravel/framework v6.0.0
    - Conclusion: don't install laravel/framework v6.0.0

**Comment by vishalinfyom** [comment]
@fgreinus PR putted for this : https://github.com/appointer/swaggervel/pull/26

**Comment by fgreinus** [comment]
Merged in v2.5.
