### ISSUE TITLE
Change route closures

### ISSUE THREAD

**Issue by w0rd-driven** [appointer/Swaggervel#4]
When running the command `php artisan route:cache` to gain a speed improvement, the /docs or whatever route is defined breaks. I'm not sure if it's because the routes are closures and don't get compiled in or if there's some extra magic that has to be done for package routes. I know if you use closures in your main routing `route:cache` fails to execute properly.

I may be able to put in the work for the PR but I wanted to make you aware in the event you've come across it before.

**Comment by fgreinus** [comment]
I did not run into that specific problem before, but will have a look asap.

What Laravel Version are you using? So it's easier for me to try to reproduce.

Thanks for you report whatsoever :)

**Comment by w0rd-driven** [comment]
It could be user error but whenever I cache the routes the swagger UI route breaks. I get the typical Sorry something went wrong. If you `route:clear` it works. I'm on 5.3 currently. I suspect because the routes are closures they're just not put into the compiled routes file.

**Comment by fgreinus** [comment]
Yeah same error here. The problem will definitely be the closures...

I'll try to fix asap :).

**Comment by fgreinus** [comment]
Has been fixed in 1.2.1.

Thanks again for the report and the explanations!
