### ISSUE TITLE
Suggestion: Add the $apiKey to the input_apiKey value

### ISSUE THREAD

**Issue by w0rd-driven** [appointer/Swaggervel#5]
On [line 154](https://github.com/appointer/Swaggervel/blob/master/src/views/index.blade.php#L154) in my view I've added `value="{!! $apiKey !!}"` which sets the value to the `config("swaggervel.api-key")`. As a side effect, [line 119](https://github.com/appointer/Swaggervel/blob/master/src/views/index.blade.php#L119) gets set on page load and I can test routes immediately without the need to click the `Explore` button.

In Chrome, the placeholder immediately goes away as I start typing so using an actual key instead of `auth_key` is difficult to deal with.

I have no problem continuing to use my custom behavior but I thought it would be beneficial to the project.

**Comment by fgreinus** [comment]
I guess that already is the current default. Maybe you have not yet published the newest version of the view files :).
