### ISSUE TITLE
Call to undefined method Jlapp\Swaggervel\Http\Controllers\SwaggervelController::getMiddleware()

### ISSUE THREAD

**Issue by manik005** [appointer/Swaggervel#6]
When I try to run `php artisan route:list` it throws the below error. what could be the problem ?
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Jlapp\Swaggervel\Http\Controllers\SwaggervelContro
  ller::getMiddleware()
`
Thanks

**Comment by fgreinus** [comment]
Hey!

What Laravel Version are you using?

**Comment by manik005** [comment]
its 5.1.45
