### ISSUE TITLE
Working with oAuth

### ISSUE THREAD

**Issue by artisaninweb** [appointer/swaggervel#8]
Is there a way to use Swagger UI with oAuth?

**Comment by fgreinus** [comment]
Basically yes. SwaggerUI supports that, But it is still in a work in progress state when i checked the last time. I'all recheck and see what i can do.

**Comment by artisaninweb** [comment]
That would be great, thanks!

**Comment by w0rd-driven** [comment]
I believe https://github.com/swagger-api/swagger-ui/blob/master/dist/oauth2-redirect.html may be a key component for this as I see it used in issues like https://github.com/swagger-api/swagger-ui/issues/3172. It also looks like the other swagger laravel package does seem to expose this via https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/Http/Controllers/SwaggerController.php#L74. The route for this is set in the index and it looks like it just serves up that file as-is. The PR number 66 (trying not to link it in case you don't want it) also seems to suggest why the file is necessary.

I'm too invested to bother switching to the other project and I think there's enough useful differences to set them both apart. I have a current need for this in a project but I don't have the time to work up a PR as quickly as I'd like. If I can get some of the more pressing concerns buttoned up, like having docs built out, I'll circle back around and see if I can work something out.

**Comment by fgreinus** [comment]
Solved in the 2.1-release: https://github.com/appointer/swaggervel/releases/tag/v2.1
